### ISSUE TITLE
Annotation ConcurrentModificationException during compilation

### ISSUE THREAD

**Issue by kmader** [scijava/scijava-common#136]
I have added a few more annotations to my project using the ```org.scijava.annotations``` tool and it now is throwing a strange ```java.util.ConcurrentModificationException``` during compilation. Has anyone seen this error before? Running a full clean on the project doesn't seem to alleviate the error.

```
Error:scala: An annotation processor threw an uncaught exception.
Error:scala: Consult the following stack trace for details.
Error:scala: java.util.ConcurrentModificationException
Error:scala: 	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1207)
Error:scala: 	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1243)
Error:scala: 	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1238)
Error:scala: 	at org.scijava.annotations.AbstractIndexWriter.write(AbstractIndexWriter.java:95)
Error:scala: 	at org.scijava.annotations.AnnotationProcessor.process(AnnotationProcessor.java:91)
Error:scala: 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
Error:scala: 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
Error:scala: 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
Error:scala: 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
Error:scala: 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
Error:scala: 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
Error:scala: 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
Error:scala: 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
Error:scala: 	at com.sun.tools.javac.main.Main.compile(Main.java:381)
Error:scala: 	at com.sun.tools.javac.main.Main.compile(Main.java:370)
Error:scala: 	at com.sun.tools.javac.main.Main.compile(Main.java:361)
Error:scala: 	at com.sun.tools.javac.Main.compile(Main.java:56)
Error:scala: 	at com.sun.tools.javac.Main.main(Main.java:42)
```

**Comment by ctrueden** [comment]
Fixed in 084f2ba71f0bb89a8487f1d83b4150cbfc4af39d. Thanks for the patch, @kmader!
