### ISSUE TITLE
error DefaultUIService #@input File 

### ISSUE THREAD

**Issue by manerotoni** [scijava/scijava-common#357]
Dear all, dear @ctrueden,   

the script command for a single file chooser
`#@input File (label ="File name") myFile`
gives following error if `File` is the only parameter passed:

```
[ERROR] Module threw exception
java.lang.NullPointerException
	at org.scijava.ui.UserInterface.chooseFile(UserInterface.java:165)
	at org.scijava.ui.DefaultUIService.chooseFile(DefaultUIService.java:313)
	at org.scijava.ui.FilePreprocessor.process(FilePreprocessor.java:71)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:105)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:157)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

If you specify an additional parameter, e.g. 

```
#@input File (label ="File name") myFile
#@input String aString
```
then it works.

Greetings

antonio

**Comment by imagejan** [comment]
This is fixed in https://github.com/scijava/scijava-common/commit/e6e1fe9f50397b3697712676d79d812fedd96aef and part of `scijava-common-2.78.0`, but not yet uploaded to the update site.

See also [this forum topic](https://forum.image.sc/t/error-for-file-type-imagej2-parameter/25585?u=imagejan).
