### ISSUE TITLE
Add a new parameter to a script, get a NPE

### ISSUE THREAD

**Issue by bogovicj** [scijava/scijava-common#381]
Create and run this script:
```
#@ Dataset (label="img") img
println( img )
```
all is well.

Edit the script (adding a parameter):
```
#@ Dataset (label="img") img
#@ File( label="file") f
println( img )
println( f )
```

get exception:
```
[ERROR] Module threw exception
java.lang.NullPointerException
	at org.scijava.ui.UserInterface.chooseFile(UserInterface.java:165)
	at org.scijava.ui.DefaultUIService.chooseFile(DefaultUIService.java:313)
	at org.scijava.ui.FilePreprocessor.process(FilePreprocessor.java:71)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:105)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:157)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] null
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.scijava.ui.swing.script.TextEditor.evalScript(TextEditor.java:2713)
	at org.scijava.ui.swing.script.TextEditor.access$600(TextEditor.java:177)
	at org.scijava.ui.swing.script.TextEditor$5.execute(TextEditor.java:2189)
	at org.scijava.ui.swing.script.TextEditor$Executer$1.run(TextEditor.java:1964)
Caused by: java.lang.NullPointerException
	at org.scijava.ui.UserInterface.chooseFile(UserInterface.java:165)
	at org.scijava.ui.DefaultUIService.chooseFile(DefaultUIService.java:313)
	at org.scijava.ui.FilePreprocessor.process(FilePreprocessor.java:71)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:105)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:157)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Maybe this has something to with the parameters being filled with their previous values?

**Comment by imagejan** [comment]
Possible duplicate of #357.

@bogovicj which version of `scijava-common` are you using? Did you try with `>=2.78.0`?

**Comment by bogovicj** [comment]
Thanks, didn't see that one ;)
This was with `scijava-common-2.77.0.jar`, I'll try with a newer one...

**Comment by bogovicj** [comment]
Not experiencing this with `scijava-common-2.79.1.jar`, thanks as always @imagejan !
