### ISSUE TITLE
Fiji won't quit when using SJC >= 2.93.0

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-common#463]
Potentially with the addition of [this commit](https://github.com/scijava/scijava-common/commit/0f6f9164eee16923b98cebf143727138281b829c), when running Fiji the shutdown process now takes significantly longer to actually complete.

This makes it possible to do horrible things like click the "X" to close Fiji multiple times.

When this happens, Fiji does the opposite and does not quit at all.

MCVE on Windows with an up-to-date Fiji 2.9.0:
1. Replace `jars/scijava-common-2.90.1.jar` with `scijava-common-2.93.0` or newer
2. Launch Fiji (easiest to see if done from the command line, e.g. `./ImageJ-win64.exe`)
3. Search for something in the search bar (if this step is omitted, the shutdown process is too quick)
4. Click the "X" multiple times to close Fiji

Eventually the GUI will disappear but the process will continue. It doesn't respond to kill signals from the terminal for me, but had to be `Ctrl+Alt+Deleted`.

Adding `-Dscijava.log.level=debug` did not show any stack trace.

Under normal shutdown conditions I see this message:
```
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
```

which is not shown if Fiji gets stuck.

**Notes**
Also tested with `jgo sc.fiji:fiji:2.12.0+org.scijava:scijava-common:2.94.0` but when running from `jgo`, and not the native launcher, the shutdown process is too fast to get multiple clicks in.

When testing with the native launcher and SJC <=2.92.0, shutdown was too fast to get multiple clicks in.

**Comment by hinerm** [comment]
From a thread dump it looks like we have two `Quit` threads that have deadlocked the EDT:

```
"Quit" #42 prio=5 os_prio=0 tid=0x0000000031d49800 nid=0x3778 in Object.wait() [0x00000000456ff000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1343)
        - locked <0x000000034b2020b0> (a java.awt.EventQueue$1AWTInvocationLock)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
        at net.imagej.legacy.IJ1Helper.closeImageWindows(IJ1Helper.java:1421)
        at net.imagej.legacy.IJ1Helper.dispose(IJ1Helper.java:250)
        - locked <0x000000037488b990> (a net.imagej.legacy.IJ1Helper)
        at net.imagej.legacy.LegacyService.dispose(LegacyService.java:519)
        at org.scijava.Context.doDispose(Context.java:597)
        - locked <0x00000003707c0220> (a org.scijava.Context)
        at org.scijava.Context.dispose(Context.java:431)
        at net.imagej.legacy.DefaultLegacyHooks.disposing(DefaultLegacyHooks.java:584)
        at ij.ImageJ.run(ImageJ.java:864)
        at java.lang.Thread.run(Thread.java:748)
```

```
"Quit" #44 prio=5 os_prio=0 tid=0x0000000031d47000 nid=0x2360 in Object.wait() [0x00000000416bf000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Thread.join(Thread.java:1252)
        - locked <0x000000034d8db0c0> (a java.lang.Thread)
        at java.lang.Thread.join(Thread.java:1326)
        at java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:107)
        at java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
        at java.lang.Shutdown.runHooks(Shutdown.java:123)
        at java.lang.Shutdown.sequence(Shutdown.java:167)
        at java.lang.Shutdown.exit(Shutdown.java:212)
        - locked <0x000000037195fae8> (a java.lang.Class for java.lang.Shutdown)
        at java.lang.Runtime.exit(Runtime.java:109)
        at java.lang.System.exit(System.java:973)
        at ij.ImageJ.run(ImageJ.java:867)
        at java.lang.Thread.run(Thread.java:748)
```

```
"AWT-EventQueue-0" #17 prio=6 os_prio=0 tid=0x0000000033f65800 nid=0x2f10 runnable [0x000000003969d000]
   java.lang.Thread.State: RUNNABLE
        at sun.awt.windows.WInputMethod.getNativeLocale(Native Method)
        at sun.awt.windows.WInputMethod.<init>(WInputMethod.java:124)
        at sun.awt.windows.WInputMethodDescriptor.createInputMethod(WInputMethodDescriptor.java:97)
        at sun.awt.im.InputContext.getInputMethodInstance(InputContext.java:855)
        at sun.awt.im.InputContext.getInputMethod(InputContext.java:805)
        - locked <0x000000034adf0a18> (a sun.awt.im.InputMethodContext)
        at sun.awt.im.InputContext.dispatchEvent(InputContext.java:240)
        at sun.awt.im.InputMethodContext.dispatchEvent(InputMethodContext.java:196)
        at java.awt.Component.dispatchEventImpl(Component.java:4821)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1023)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:689)
        at java.awt.Component.dispatchEventImpl(Component.java:4760)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at sun.awt.SunToolkit$1.run(SunToolkit.java:521)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I'll keep looking at how to fix this

**Comment by hinerm** [comment]
OK, so this line calls `System.exit`:
```
        at ij.ImageJ.run(ImageJ.java:867)
```

When clicking repeatedly on the "X" to close Fiji, eventually a `CausedFocusEvent` is propagated along the IJ search bar (`LegacySearchBar` in `AWT-EventQueue` above). If this happens *after* `System.exit` is called the thread will deadlock itself.

I thought we might be able to do something on the [IJ-legacy side](https://github.com/imagej/imagej-legacy/blob/2569e64efaf50bd574338d0f7514dd38b337f910/src/main/java/net/imagej/legacy/IJ1Helper.java#L250) but *that* `Quit` thread (`#42` above) is also deadlocked because of the EDT deadlock, and its `ij` field is already `null` anyway.

So somehow the second `Quit` thread (`#44` above) is also being launched on the subsequent "X" clicks, going right to `System.exit`, and causing everything else to lock up...

My next direction is to find exactly what's launching this second thread and maybe finding a way to stop it.

I can say this: when debugging, if I breakpoint at the `System.exit` and don't allow that to proceed until the EDT has cleared its `CausedFocusEvent`, then the system shuts down appropriately.

**Comment by hinerm** [comment]
OK what's happening is that each time you click the "X" in ImageJ you call its [`quit()`](https://github.com/imagej/ImageJ/blob/8d46a009fbc4c1d39af3b729b9ba24b465e223a4/ij/ImageJ.java#L700) method. This eventually delegates to [`DefaultLEgacyHooks.disposing()`](https://github.com/imagej/imagej-legacy/blob/2569e64efaf50bd574338d0f7514dd38b337f910/src/main/java/net/imagej/legacy/DefaultLegacyHooks.java#L569-L587).

The first threads that hits `disposing()` will start the actual context shut down. Subsequent threads will return immediately since the context is in the process of shutting down. However, this allows ImageJ to then immediately proceed to its [`System.exit()`](https://github.com/imagej/ImageJ/blob/master/ij/ImageJ.java#L867-L869) call.

When `System.exit()` is called while the SJC context is disposing the deadlock arises.

**Comment by ctrueden** [comment]
> When `System.exit()` is called while the SJC context is disposing the deadlock arises.

@hinerm Interesting! Do you know why? That seems like a bug to me, which we should try to address.
